//------------------------------------------------------------------------------
// <auto-generated>
//     если использовать тег copyright то появляются ошибки. пока что не разобрался как это исправить
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW09_Threads_Rec
{
    /// <summary>
    /// Класс, запускающий бесконечную рекурсию и создание новых потоков.
    /// </summary>
    internal class Program
    {
        /// <summary>
        /// Точка входа в программу.
        /// </summary>
        /// <param name="args">Аргументы командной строки.</param>
        public static void Main(string[] args)
        {
            Thread thread = new Thread(Threads_Rec);
            thread.IsBackground = true;
            thread.Start();
            thread.Join();
        }

        /// <summary>
        /// рекурсивный метод. каждая итерация в новом потоке.
        /// </summary>
        private static void Threads_Rec()
        {
            Thread thread = new Thread(Threads_Rec);
            thread.IsBackground = true;
            thread.Start();
            Console.WriteLine("id: " + Thread.CurrentThread.ManagedThreadId);
            Console.WriteLine("count: " + System.Diagnostics.Process.GetCurrentProcess().Threads.Count);
            thread.Join();
        }
    }
}